version: '3'

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: db-mysql
    command: --innodb-use-native-aio=0
    tty: true
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challengedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 20s
      timeout: 10s
      retries: 3
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - challenge
    environment:
      - DB_HOST=db-mysql
      - DB_NAME=challengedb
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
  proxy:
    image: nginx
    container_name: nginx-proxy
    tty: true
    restart: always
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - challenge
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

networks:
  challenge:
    driver: bridge
